version: '3'
services:
  tests: &tests
    build: .
    image: keboola-component-db-writer-hive
    command: composer ci
    environment:
      # Db credentials
      HIVE_DB_HOST: ${HIVE_DB_HOST:-hive-server}
      HIVE_DB_PORT: ${HIVE_DB_PORT:-10000}
      HIVE_DB_DATABASE: ${HIVE_DB_DATABASE:-default}
      HIVE_DB_USER: ${HIVE_DB_USER:-hive}
      HIVE_DB_PASSWORD: ${HIVE_DB_PASSWORD:-p#a!s@sw:o&r%^d} # defined in docker/ldap/init/01-hive-user.ldif
      HIVE_VERSION: ${HIVE_VERSION:-2.3.6}
      # SSH container credentials
      SSH_DB_HOST: hive-server-behind-ssh
      SSH_HOST: ssh-tunnel
      SSH_PORT: 22
      SSH_USER: root
    links:
      - hive-server
      - ssh-tunnel
    volumes:
      - ssh-keys:/root/.ssh:ro

  dev:
    <<: *tests
    command: bash
    volumes:
      - ./:/code
      - ssh-keys:/root/.ssh:ro

  wait:
    image: waisbrot/wait
    depends_on:
      - hive-server
      - ssh-tunnel
    environment:
      - TARGETS=hive-server:10000,ssh-tunnel:22
      - TIMEOUT=120

  # SSH tunnel
  ssh-tunnel:
    image: keboola/db-component-ssh-proxy:latest
    volumes:
      - ssh-keys:/root/.ssh
    links:
      - hive-server:hive-server-behind-ssh

  # LDAP authentication server for Hive (external auth must be provided)
  # Test cmd: docker-compose exec ldap ldapsearch -x -H ldap://localhost -b dc=keboola-test,dc=com -D "uid=admin,dc=keboola-test,dc=com" -w 'admin'
  # Modify command: docker-compose exec ldap ldapmodify -H ldap://localhost -D "uid=admin,dc=keboola-test,dc=com" -w 'admin'
  ldap:
    image: osixia/openldap:1.3.0-amd64
    command: --copy-service
    environment:
      LDAP_TLS: 'false'
      LDAP_ORGANISATION: Keboola Test
      LDAP_DOMAIN: keboola-test.com
      LDAP_ADMIN_PASSWORD: admin
    volumes:
      # Older Hive DB versions requires user RDN in format uid=user,... not cn=user,...
      - ./docker/ldap/init:/container/service/slapd/assets/config/bootstrap/ldif/custom:ro

  # Hive infrastructure
  # From: https://github.com/big-data-europe/docker-hive/blob/master/docker-compose.yml
  # Test cmd: docker-compose exec hive-server beeline -u jdbc:hive2://localhost:10000 -n admin -p 'admin' -e "SHOW TABLES;"
  hive-server:
    image: hive-server
    build:
      context: docker/hive-server
      args:
        HIVE_VERSION: ${HIVE_VERSION:-2.3.6}
    env_file:
      - docker/hive-server/hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "hive-metastore:9083"
    links:
      - ldap
      - namenode
      - datanode
      - hive-metastore
      - hive-metastore-postgresql
  hive-metastore:
    image: hive-server
    build:
      context: docker/hive-server
      args:
        HIVE_VERSION: ${HIVE_VERSION:-2.3.6}
    env_file:
      - docker/hive-server/hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
  hive-metastore-postgresql:
    image: postgres:9.5.3
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    environment:
      - CLUSTER_NAME=test
    env_file:
      - docker/hive-server/hadoop-hive.env
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    env_file:
      - docker/hive-server/hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"

volumes:
  ssh-keys:
